### ISSUE TITLE
HU15 - Reserva: Pago con Tarjeta

### ISSUE THREAD

**Issue by jliriano** [jliriano/miw-mdw-ml#9]
Como un cliente, 
necesito poder efectuar el pago con tarjeta, 
con la finalidad de finalizar la reserva y garantizar mi derecho al disfrute de la habitación instantaneamente

**Tarea 1** - Agregar pago con tarjeta a proceso de Reserva

Detalle tareas: https://docs.google.com/spreadsheets/d/1d12p2TLc4WtP7u8H0OQnfYSmxkNglpRbMjwKuI_ZeB8/edit#gid=1376323238

**Comment by b2lero** [comment]
El proceso de pago ya fue integrado con la issue #8
